# Generated by Django 5.2.8 on 2025-11-20 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamados',
            old_name='descriacao',
            new_name='descricao',
        ),
    ]
