# Generated by Django 5.2.8 on 2025-11-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_rename_descriacao_chamados_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamados',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('Em_ANDAMENTO', 'Em_Andamento'), ('FEXADO', 'Fexado')], default='ABERTO', max_length=13),
        ),
    ]
