# Generated by Django 5.2.8 on 2026-01-06 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0004_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='tipo',
        ),
    ]
